# This is a basic workflow to help you get started with Actions
name: DAYLIGHT CHECKER
# Controls when the workflow will run
on:
  schedule:
   - cron: "6 14 * * 1-5"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # set the environment variables
      - name: SET BST ENV VAR
        run: echo "BST_ENV_VAR=$(TZ='Europe/London' date)" >> $GITHUB_ENV
      - name: SET UTC ENV VAR
        run: echo "UTC_ENV_VAR=$(date)" >> $GITHUB_ENV 
        
      # Runs DAYLIGHT SAVING FALSE command using the runners shell
      - name: IT IS NOT DAYLIGHT SAVING
        if: ${{ env.BST_ENV_VAR == env.UTC_ENV_VAR }}
        run: echo "IT IS WINTER TIME"

      # Runs DAYLIGHT SAVING TRUE using the runners shell
      - name: IT IS DAYLIGHT SAVING
        if: ${{ env.BST_ENV_VAR != env.UTC_ENV_VAR }}
        run: |
            curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/lekeDevOps/lekeDevOps/actions/workflows/54820689/enable
            curl -L -X PUT -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GH_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/lekeDevOps/lekeDevOps/actions/workflows/54820804/disable      
